apiVersion: v1
kind: Service
metadata:
  name: gift-suggestion-np-srv
spec:
  type: NodePort
  selector:
    app: gift-suggestion-service
  ports:
    - name: gift-suggestion-service
      protocol: TCP
      port: 5001
      targetPort: 5001
