apiVersion: v1
kind: Service
metadata:
  name: giftSuggestionnpservice-srv
spec:
  type: NodePort
  selector:
    app: giftSuggestionservice
  ports:
    - name: giftSuggestionservice
      protocol: TCP
      port: 80
      targetPort: 80