apiVersion: apps/v1
kind: Deployment
metadata:
  name: givr-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: givr-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: givr-ui
    spec:
      containers:
        - name: givr-ui
          image: givrprodacr.azurecr.io/givr-ui:latest
          resources:
            requests:
              cpu: 150m
              memory: 250Mi
            limits:
              cpu: 85m # Adjusted to match the available CPU capacity of the single node
              memory: "1Gi" # Adjusted to fit within the available Memory capacity
          ports:
            - containerPort: 8080
            - containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: givr-ui
  namespace: default
spec:
  selector:
    app: givr-ui
  type: ClusterIP
  ports:
    - name: givr-ui
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: givr-ui-https
      protocol: TCP
      port: 443
      targetPort: 443
