apiVersion: v1
kind: Service
metadata:
  name: ui-loadbalancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: gift-genius-prod-infra
    # service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.loadbalancer.dnsLabel }}
spec:
  type: LoadBalancer
  loadBalancerIP: 20.9.21.31
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: givr-ui
  selector:
    app: givr-ui
